name: annakushnerova
favicon: null
layout_spectrum: 0.9884838487487286
typography_spectrum: 0.40035169501788914
title: annakushnerova
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  brandStrength: 0.4895718526095152
  lightness: 0.930828110082075
  saturation: 0.7588939291890711
  rhythmicContrast: 0.8735729705076665
purpose: []
