name: annakushnerova
favicon: null
layout_spectrum: 0.00124
typography_spectrum: 0.49381
title: annakushnerova
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#f1eee9'
    - '#c9c6bd'
    - '#3b413d'
    - '#67726e'
  brandStrength: 0.815218583215028
  lightness: 0.5243188652675599
  saturation: 0.8936950957868248
  rhythmicContrast: 0.580408944748342
purpose: []
